 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/table_symplis", type: :request do
  # TableSympli. As you add validations to TableSympli, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TableSympli.create! valid_attributes
      get table_symplis_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      table_sympli = TableSympli.create! valid_attributes
      get table_sympli_url(table_sympli)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_table_sympli_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      table_sympli = TableSympli.create! valid_attributes
      get edit_table_sympli_url(table_sympli)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TableSympli" do
        expect {
          post table_symplis_url, params: { table_sympli: valid_attributes }
        }.to change(TableSympli, :count).by(1)
      end

      it "redirects to the created table_sympli" do
        post table_symplis_url, params: { table_sympli: valid_attributes }
        expect(response).to redirect_to(table_sympli_url(TableSympli.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TableSympli" do
        expect {
          post table_symplis_url, params: { table_sympli: invalid_attributes }
        }.to change(TableSympli, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post table_symplis_url, params: { table_sympli: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested table_sympli" do
        table_sympli = TableSympli.create! valid_attributes
        patch table_sympli_url(table_sympli), params: { table_sympli: new_attributes }
        table_sympli.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the table_sympli" do
        table_sympli = TableSympli.create! valid_attributes
        patch table_sympli_url(table_sympli), params: { table_sympli: new_attributes }
        table_sympli.reload
        expect(response).to redirect_to(table_sympli_url(table_sympli))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        table_sympli = TableSympli.create! valid_attributes
        patch table_sympli_url(table_sympli), params: { table_sympli: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested table_sympli" do
      table_sympli = TableSympli.create! valid_attributes
      expect {
        delete table_sympli_url(table_sympli)
      }.to change(TableSympli, :count).by(-1)
    end

    it "redirects to the table_symplis list" do
      table_sympli = TableSympli.create! valid_attributes
      delete table_sympli_url(table_sympli)
      expect(response).to redirect_to(table_symplis_url)
    end
  end
end
